name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  RUST_VERSION: stable  # Use 'stable',
  CARGO_TERM_COLOR: always


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo clippy
    - name: Fix
      run: cargo clippy --fix --allow-dirty
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
